# Utilisation de l'image Node.js v14
FROM node:14

# Création du répertoire de travail
WORKDIR /app

# Copie des fichiers de package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm install

# Copie des fichiers du projet
COPY . .

# Exposition du port 3000 pour l'interface développeur
EXPOSE 3000

# Commande de démarrage de l'application
CMD ["npm", "start"]
